export const ActionNameList = {
    // 書籍検索
    searchBookRequested: "SEARCH_BOOK_REQUESTED",
    searchBookSucceeded: "SEARCH_BOOK_SUCCEEDED",
    searchBookError: "SEARCH_BOOK_ERROR",
    // レビュー投稿
    postReviewRequested: "POST_REVIEW_REQUESTED",
    postReviewSucceeded: "POST_REVIEW_SUCCEEDED",
    postReviewError: "POST_REVIEW_ERROR",
    // レビュー取得
    getReviewRequested: "GET_REVIEW_REQUESTED",
    getReviewSucceeded: "GET_REVIEW_SUCCEEDED",
    getReviewError: "GET_REVIEW_EROOR",
    // 気になる投稿
    postBookLikeRequested: "POST_BOOKLIKE_REQUESTED",
    postBookLikeSucceeded: "POST_BOOKLIKE_SUCCEEDED",
    postBookLikeError: "POST_BOOKLIKE_ERROR",
    // 気になる取得
    getBookLikeRequested: "GET_BOOKLIKE_REQUESTED",
    getBookLikeSucceeded: "GET_BOOKLIKE_SUCCEEDED",
    getBookLikeError: "GET_BOOKLIKE_EROOR",
    // 最新書籍取得
    getLatestBooksRequested: "GET_LATEST_BOOKS_REQUESTED",
    getLatestBooksSucceeded: "GET_LATEST_BOOKS_SUCCEEDED",
    getLatestBooksError: "GET_LATEST_BOOKS_ERROR",
    // BookIDから特定の書籍を取得
    getBookInfoByBookidRequested: "GET_BOOKINFO_BY_BOOKID_REQUESTED",
    getBookInfoByBookidSucceeded: "GET_BOOKINFO_BY_BOOKID_SUCCEEDED",
    getBookInfoByBookidError: "GET_BOOKINFO_BY_BOOKID_ERROR",
    // 書籍テーブルからレビュー数気になる数取得
    getAppInfoForBooksRequested: "GET_APP_INFO_FOR_BOOKS_REQUESTED",
    getAppInfoForBooksSucceeded: "GET_APP_INFO_FOR_BOOKS_SUCCEEDED",
    getAppInfoForBooksError: "GET_APP_INFO_FOR_BOOKS_ERROR",
    // レビュー履歴取得
    getUserReviewsRequested: "GET_USER_REVIEWS_REQUESTED",
    getUserReviewsSucceeded: "GET_USER_REVIEWS_SUCCEEDED",
    getUserReviewsError: "GET_USER_REVIEWS_ERROR",
    // 気になる履歴取得
    getUserLikesRequested: "GET_USER_LIKES_REQUESTED",
    getUserLikesSucceeded: "GET_USER_LIKES_SUCCEEDED",
    getUserLikesError: "GET_USER_LIKES_ERROR",
}
