export const ActionNameList = {
    searchBookRequested   : "SEARCH_BOOK_REQUESTED",
    searchBookSucceeded   : "SEARCH_BOOK_SUCCEEDED",
    searchBookError       : "SEARCH_BOOK_ERROR",
    postReviewRequested   : "POST_REVIEW_REQUESTED",
    postReviewSucceeded   : "POST_REVIEW_SUCCEEDED",
    postReviewError       : "POST_REVIEW_ERROR",
    getReviewRequested    : "GET_REVIEW_REQUESTED",
    getReviewSucceeded    : "GET_REVIEW_SUCCEEDED",
    getReviewError        : "GET_REVIEW_EROOR",
    postBookLikeRequested : "POST_BOOKLIKE_REQUESTED",
    postBookLikeSucceeded : "POST_BOOKLIKE_SUCCEEDED",
    postBookLikeError     : "POST_BOOKLIKE_ERROR",
    getBookLikeRequested  : "GET_BOOKLIKE_REQUESTED",
    getBookLikeSucceeded  : "GET_BOOKLIKE_SUCCEEDED",
    getBookLikeError      : "GET_BOOKLIKE_EROOR",
}
